[tool.black]
line-length = 88
target-version = ['py312']
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.venv
  | venv
  | env
  | \.git
  | \.mypy_cache
  | \.pytest_cache
  | \.vscode
  | build
  | dist
  | migrations
)/
'''
